# Generated by Django 5.0.3 on 2024-04-03 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0052_organizationvisithistory_visit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationbranch',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='organizationbranch',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
